### ISSUE TITLE
Can you provide a bibtex citation for this repository?

### ISSUE THREAD

**Issue by zifanw** [LarsHoldijk/RE-ParameterizedExplainerForGraphNeuralNetworks#1]
Hi, 

Thanks for great work that provides feasible and simple APIs to use the GNN paper and PG paper. For the convenience when using your great work, do you mind providing a bibtex citation so people can cite your work properly or you prefer mentioning this work just with GitHub link?

Thanks!

**Comment by HosseinMousavi** [comment]
> Hi,
> 
> Thanks for great work that provides feasible and simple APIs to use the GNN paper and PG paper. For the convenience when using your great work, do you mind providing a bibtex citation so people can cite your work properly or you prefer mentioning this work just with GitHub link?
> 
> Thanks!

Hi Zifanw,
I really appreciate it if you could help me!
I am trying to use these code base to explain the GNN (GNNExplainer), I just need graph classification.
I have one dataset, it is just one file. I am asking if I should provide more dataset/information to be able to use these codes?
Foe example: graph.labels, graph indicators, and ....

I really appreciate your help!
Hossein

**Comment by LarsHoldijk** [comment]
Hi Zifanw! 

Thanks for asking about this. I bet it is probably too late for you at this point, but the correct bibtex would be

`@inproceedings{holdijk2021re,
  title={[Re] Parameterized Explainer for Graph Neural Network},
  author={Holdijk, Lars and Boon, Maarten and Henckens, Stijn and de Jong, Lysander},
  booktitle={ML Reproducibility Challenge 2020},
  year={2021}
}
`

**Comment by LarsHoldijk** [comment]
> > Hi,
> > Thanks for great work that provides feasible and simple APIs to use the GNN paper and PG paper. For the convenience when using your great work, do you mind providing a bibtex citation so people can cite your work properly or you prefer mentioning this work just with GitHub link?
> > Thanks!
> 
> Hi Zifanw, I really appreciate it if you could help me! I am trying to use these code base to explain the GNN (GNNExplainer), I just need graph classification. I have one dataset, it is just one file. I am asking if I should provide more dataset/information to be able to use these codes? Foe example: graph.labels, graph indicators, and ....
> 
> I really appreciate your help! Hossein

Hi Hossein, 
Please open a new issue if you still need help with this.
