### ISSUE TITLE
GNNExplainer syn3 dataset low score

### ISSUE THREAD

**Issue by seakkas** [LarsHoldijk/RE-ParameterizedExplainerForGraphNeuralNetworks#2]
Hi,

Great replication work. It is easy to follow the code.

I am trying to replicate GNNExplainer results. I am unable to get any good results for the syn3 dataset (tree cycles) with the latest version of pyg (2.0.4). The score is about 0.5. I tried to retrain the model but had no luck. Can you specify the pyg version? Also, can you test it with the latest version of pyg?

Btw, I had to modify the `model_selector` function to load pre-trained checkpoints for pyg 2.0.4. No modification is needed if the model is retrained.

My modification:
```
renamed_state_dict = {}
for key in checkpoint['model_state_dict']:
    if key.startswith('conv') and key.endswith('weight'):
        new_key = key[:5] + '.lin' + key[5:]
        renamed_state_dict[new_key] = (checkpoint['model_state_dict'][key]).T
    else:
        renamed_state_dict[key] = checkpoint['model_state_dict'][key]
model.load_state_dict(renamed_state_dict)
```

Thanks

**Comment by wOvOpy** [comment]
I had the same problem with you. Did you solve it?

**Comment by seakkas** [comment]
The authors show that GNNExplainer does not give the same result as the original paper. Please refer to the report here: https://openreview.net/forum?id=8JHrucviUf.
I opened this issue before thoroughly reading the report; then, I forgot to close the issue.

Table 2 from the report is below. The authors get  0.540 for the tree cycles dataset.
<img width="739" alt="image" src="https://user-images.githubusercontent.com/16028577/172776435-a5303e26-4cbc-486f-bbd5-4bc426b7cd8e.png">

**Comment by farahFif** [comment]
Hi, 
Thank you for sharing the useful insights. However, my problem now is not only with treecycle dataset but with all other datasets I cannot reproduce the results for GNNExplainer. For PGExplainer it works well, but not GNNExplainer do you have any idea about this ? 
Thank you

**Comment by seakkas** [comment]
Hi,

The results depend on the seeds you use. Without seeds, I got the following ROC-AUC scores: 
| Explainer    | BA Shapes  | Tree Cycle | Tree Grid  |
| ------------ | ---------- | ---------- | ---------- |
| GNNExplainer | 0.624±0.02 | 0.523±0.02 | 0.543±0.01 |

**Comment by farahFif** [comment]
Hi,

I tried to run experiment_replication.ipynb and it provides scores for many seeds but none of them reached what is mentioned. Except for PGExplainer it works fine.
